# Site settings
## Change the values as needed.
title: "StuSerrl_blog"
email: solio2@daum.net
description: "Front-End, Back-End FOR JS"
keywords: "Front-End, Back-End, JS"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: https://www.facebook.com/profile.php?id=100011382379685
  twitter: 
  email: solio2@daum.net
  github: https://github.com/SERRL
exclude:
  - bower_components
  - README.md
full_name: Brijesh

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
